notifications:
  email: false

dist: trusty
language: c
compiler: gcc

cache:
  directories:
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: "tot0k-github"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y lcov libcmocka0 libcmocka-dev cppcheck

before_script:
  # CppCheck
  - cppcheck --enable=all --force test/ src/
  # CMake
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make clean

script:
  # Build with SonarCloud
  - build-wrapper-linux-x86-64 --out-dir bw_output make
  - make coverage
  - cd ..
  - sonar-scanner
